services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - 9090:9090"
    volumes:
      - /infra/store/linkding:/etc/linkding/data"
    restart: unless-stopped
