services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - 9090:9090
    volumes:
      - /infra/store/linkding:/etc/linkding/data"
    environment:
      - LD_SUPERUSER_NAME=$LD_SUPERUSER_NAME
      - LD_SUPERUSER_PASSWORD=$LD_SUPERUSER_PASSWORD
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.linkding.entrypoints: web,websecure
      traefik.http.routers.linkding.rule: Host(`linkding.local.$DOMAIN_NAME`)
      traefik.http.routers.linkding.tls: true
