---
services:
  telegram-bot-api:
    container_name: telegram-bot-api
    image: aiogram/telegram-bot-api:latest
    ports:
      - 8081:8081
    volumes:
      - /etc/var/telegram-bot-api:/var/lib/telegram-bot-api
    environment:
      TELEGRAM_API_ID: ${TG_API_ID}
      TELEGRAM_API_HASH: ${TG_API_HASH}
    restart: unless-stopped
