services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /infra/store/jellyfin/config:/config
      - /infra/store/jellyfin/cache:/cache
      - /infra/store/jellyfin/media:/media
      - ~/Movies:/movies:ro
    environment:
      - JELLYFIN_PublishedServerUrl=jellyfin.local.$DOMAIN_NAME
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
