---
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /infra/store/redis:/data
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_PASSWORD
    restart: unless-stopped
